# Generated by Django 5.2.5 on 2025-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, help_text='例: チーム虎、開発班A、など', max_length=100, verbose_name='グループ名'),
        ),
    ]
