# Generated by Django 5.2.5 on 2025-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionevaluation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
    ]
