# Generated by Django 5.2.5 on 2025-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_group_peer_evaluation_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionevaluation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='group',
            name='peer_evaluation_deadline',
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='peer_evaluation_closed',
            field=models.BooleanField(default=False, verbose_name='ピア評価締切済み'),
        ),
    ]
