# Generated by Django 5.2.5 on 2025-09-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_remove_contributionevaluation_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('question_type', models.CharField(choices=[('multiple_choice', '選択問題'), ('true_false', '正誤問題'), ('short_answer', '記述問題')], default='multiple_choice', max_length=20, verbose_name='問題形式')),
                ('points', models.IntegerField(default=1, verbose_name='配点')),
                ('order', models.IntegerField(default=1, verbose_name='出題順')),
                ('correct_answer', models.TextField(blank=True, verbose_name='正解（記述問題用）')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school_management.quiz', verbose_name='小テスト')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('order', models.IntegerField(default=1, verbose_name='表示順')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='school_management.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢',
                'ordering': ['order'],
            },
        ),
    ]
