# Generated by Django 5.2.5 on 2025-09-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_question_questionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='furigana',
            field=models.CharField(blank=True, max_length=100, verbose_name='ふりがな'),
        ),
    ]
