# Generated by Django 5.2.5 on 2025-09-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0007_customuser_furigana'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, verbose_name='ポイント'),
        ),
    ]
