# Generated by Django 5.2.5 on 2025-09-01 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_add_furigana_and_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='QRコードID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最終使用日時')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生QRコード',
                'verbose_name_plural': '学生QRコード',
            },
        ),
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField(default=1, verbose_name='付与ポイント')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='スキャン日時')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='スキャン者')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='school_management.studentqrcode', verbose_name='QRコード')),
            ],
            options={
                'verbose_name': 'QRコードスキャン',
                'verbose_name_plural': 'QRコードスキャン',
                'unique_together': {('qr_code', 'scanned_by')},
            },
        ),
    ]
