# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0009_studentqrcode_qrcodescan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLessonPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='ポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lesson_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_points', to='school_management.lessonsession', verbose_name='授業セッション')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_points', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生授業ポイント',
                'verbose_name_plural': '学生授業ポイント',
            },
        ),
        migrations.AddField(
            model_name='qrcodescan',
            name='lesson_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='school_management.lessonsession', verbose_name='授業セッション'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlessonpoints',
            unique_together={('student', 'lesson_session')},
        ),
    ]
