# Generated by Django 5.2.7 on 2025-10-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0010_studentlessonpoints_qrcodescan_lesson_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='ポイント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class_points', to='school_management.classroom', verbose_name='クラス')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_points', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生クラスポイント',
                'verbose_name_plural': '学生クラスポイント',
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
