# Generated by Django 5.2.5 on 2025-10-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0011_studentclasspoints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrcodescan',
            unique_together=set(),
        ),
    ]
