# Generated by Django 5.2.6 on 2025-10-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0013_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasspoints',
            name='attendance_rate',
            field=models.FloatField(default=0.0, help_text='0-100の範囲', verbose_name='出席率'),
        ),
    ]
