# Generated by Django 5.2.6 on 2025-10-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0014_studentclasspoints_attendance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasspoints',
            name='attendance_points',
            field=models.FloatField(default=0.0, help_text='出席率から計算される点数', verbose_name='出席点'),
        ),
    ]
